<h1 align="center">SGI WebForce O2 is a one-stop Web authoring platform</h1>
<p align="center"><i>by Brad Morrey, InfoWorld (<a href="https://books.google.com/books?id=bjoEAAAAMBAJ&pg=PA50" target="_blank">January 20 1997, page 50</a>)</i></p>
<hr>
<p>Silicon Graphics systems aren't just for graphics and video manipulation anymore. SGI's WebForce line of servers ranges from simple Web authoring workstations to multigigabyte, scalable symmetric-multiprocessing Web servers. One of the latest members of this line, the WebForce O2, has everything a user could want to develop multimedia content for the World Wide Web.</p>
<p>The basic authoring station bundle includes SGI's Cosmo Tools suite; native versions of Adobe Photoshop, Adobe Illustrator, and MetaTools' Kai's Power Tools; and Netscape's FastTrack Server. Cosmo Tools includes Cosmo Create, a full-featured WYSIWYG HTML editor; Cosmo Code, a visual Java development environment that rivals Symantec's Visual Cafe in its functionality and ease of use; and Cosmo Worlds, which provides a development environment for creating Virtual Reality Modeling Language (VRML) 2.0 worlds. These tools, plus its easy-to-use graphical interface, make O2 a compelling platform for corporate multimedia Web and intranet development.</p>
<h2>Frames, forms and features</h2>
<p>Cosmo Create is a complete visual Web-page editor that sports many extras not found in other Web editing tools. Creating and managing HTML frames, image maps, and applets is easy with Cosmo Create. I was able to create a five-frame page with a navigation bar, complete with image maps, in almost no time.</p>
<p>Cosmo Create's form-creation window allows easy visual creation of form elements and automatic generation of a customizable Perl script to handle data submitted by the forms.</p>
<p>Creating a pane for a Java applet was as easy as sweeping out the area with the mouse and then pointing to the properties page for the applet at the correct class file. I found that if I created an applet in Cosmo Code, the HTML file to display that applet was automatically created.</p>
<p>I noticed one annoying quirk: When I pasted an applet into an HTML table, the window jumped to the bottom of the table. This is a small annoyance, however- in general, I was very impressed with the performance and stability of the three programs in the Cosmo suite.</p>
<h2>Know the code</h2>
<p>Cosmo Code is based on technology from ProDev WorkShop, SGI's C++ development environment. I found it to be very similar in feel to Symantec's Visual Cafe 1.0.</p>
<img src="img/infoworld-o2-webforce.GIF" title="SGI WebForce O2" alt="The Silicon Graphics WebForce O2 sports a flashy, high-tech exterior." align="right">
<p>All of the tools for rapid application building are included in Cosmo Code. It has a graphical debugger; a visual code analyzer for viewing relationships between classes and methods; a project manager; and a Java-aware source editor that highlights reserved words, automatically indents, matches up parenthesis, and the like.</p>
<p>Cosmo Code also sports a terrific Visual Builder for building interfaces and defining the actions associated with interface elements, either with the Wiring Manager, which automatically generates event handler code, or with a custom event handler. Cosmo Code's Visual Bulder allowed me to create a simple phone-book application in a matter of minutes.</p>
<p>The Cosmo Code environment also includes a byte-code translator for converting Java byte code into native SGI CPU instructions. SGI said this translator improves the performance of Java programs by as much as 10 times on SGI machines, SGI is also working on a just-in-time compiler for speeding the execution of applets on Web pages.</p>
<h2>3-D glasses not required</h2>
<p>Cosmo Worlds, the O2's VRML 2.0 editing tool, is easy to use and very powerful. For someone tackling a visualization problem, such as an engineering or design problem, getting a 3-D view of the design can be invaluable, and Cosmo Worlds provides tools to make that possible.</p>
<p>The tools are so intuitive that an untrained user can easily generate rich static worlds without any help at all. After some training (the product comes with a training video and a VRML 2.0 handbook), users should easily be able to create animated 3-D worlds. I was able to quickly generate a 3-D room with lighting and fill it with objects that responded to mouse clicks or collisions with other objects.</p>
<p>The VRML code that Cosmo Worlds generates can be viewed with any VRML 2.0-compliant browser, such as SGI's own Cosmo Player (a Netscape and Internet Explorer 3.0 plug-in). In addition to SGI's Cosmo Player, Netscape, Sony, and Intervista offer VRML 2.0-compatible browsers.</p>
<p>VRML 2.0 builds on VRML 1.0 functionality by adding support for collision detection, animation, interaction between elements, and other interactive elements, such as sensors and a Java interface, to allow other components to interact with VRML objects.</p>
<p>This interface and the support provided for JavaScript and Java allow programmers to develop itneractive applications that use VRML for a variety of data-access and visualizationt asks. For isntance, a user could click a JavaScript button to update a 3-D stock graph with the latest ticker information.</p>
<p>VRML 2.0 can be very processor-intensive, however. Some of the complex worlds at SGI's VRML site, which appeared fluid and realistic on the O2, rendered very slowly on a 120-MHz Pentium test system running the Windows 95 version of Cosmo Player.</p>
<h2>Finishing touches</h2>
<p>Other niceties make the O2 an excellent choice for a workgroup Web authoring workstation. The O2's native support for AppleTalk and NetWare networking allow it to pull data from your existing file servers as well as your graphics designer's or publisher's hard drives.</p>
<p>The O2's X-Windows GUI is one of the finest I've seen, providing easy-to-use graphical tools for all user and system functions. It even makes it easy to mount network resources into your directory tree. These extras make the O2 a system that should appeal to people who don't have much Unix experience because you can be productive with the system without delving into the daunting world of configuration files and daemons.</p>
<p>There are a few minor bugs. I had some trouble getting the NetWare support up and running. Apparently, there was a bug in teh graphical browser that caused Irix to crash when accessing NetWare volumes. SGI technical support fixed the crashing problem, but I was still unable to drag and drop files from the server to my desktop.</p>
<p>I ran into another problem when I installed an additional hard drive and added RAM to the motherboard: The power supply burned out, sparking and smoking in the process. SGI technicians believe this was either a freak problem with my particular power supply or else I inadvertently did something when installing the new equipment.</p>
<p>But the most telling aspect of O2 is its ease of use. I felt comfortable with its GUI environment and was able to be productive immediately with each application I tried. This instant productivity is a gold mine for content developers who don't want to spend a lot of time training.</p>
