<h1 align="center">SGI 3-D Graphics Line Leapfrogs IBM RS/6000</h1>
<h3 align="center">Power Vision to Deliver Polygon, Full-Screen Anti-Aliasing at 1 Million 3-D Vectors a Second</h3>
<p align="center"><i>by Martin Marshall, InfoWorld (<a href="https://books.google.com/books?id=gTAEAAAAMBAJ&pg=PT40" target="_blank">February 19 1991, page 41</a>)</i></p>
<hr>
<p>When IBM grabs the headlines with its RISC System/6000 workstations with 3-D graphics capability, Silicon Graphics Computer Systems Inc. (SGI) will quietly move two generations ahead of the IBM offerings this week with a new family of super-powerful 3-D graphics machines.</p>
<img src="img/infoworld-powervision-aa.GIF" title="Silicon Graphics Power Vision" alt="Silicon Graphics' Power Vision series is the first to offer 3-D polygon anti-aliasing and full-screen anti-aliasing, according to SGI. In the space station scene shown above, the enlargements show the scene without anti-aliasing (left) and with anti-aliasing (right)" align="right">
<p>The new SGI machines, the Power Vision series, will be the third generation of graphics technology offered by the company. They feature the capability to generate 1 million smooth-shaded 3-D polygons per second, or 1 million anti-aliased 3-D vectors per second.</p>
<p>The first generation, which generates 5,100 3-D polygons per second, and 91,000 3-D vectors per second, is used in the company's baseline Personal Iris workstations. The second generation Turbo Graphics delivers 24,000 to 90,000 3-D smooth-shaded polygons per second.</p>
<p>Under a September 1988 agreement with IBM, SGI will manufacture an MCA-bus version of this baseline graphics technology for the IBM RISC System/6000 series. IBM will resel the board as its Super Graphics Processor Subsystem.</p>
<p>The Power Vision series features performance of 1 million anti-aliased polygons per second, 1 million anti-aliased 3-D veectors per second, and 1 1/2 million anti-aliased points per second. New product features include real-time anti-aliasing of polygons, vectors, and points; real-time texture mapping; real-time fast Fourier transforms; and real-time special effects such as blurring and fogging.</p>
<p>The Power Vision series also includes complex lighting models and a screen clearing rate that is 10 times faster than previous systems.</p>
<p>The Power Vision series will be the new top of the company's line, priced from $94,900 to $224,400. At the same time, SGI will push down the pricing on its Turbo Graphics GTX series, starting the Model 4D/210GTXB at $74,900.</p>
<p>Earlier this month, SGI announced an intermediate-level system, the Model 4D/85GTB, that generates 400,000 3-D vectors per second, or 90,000 3-D polygons per second. It has 48-bit-per-pixel color resolution, with a 24-bit Z buffer. At a base price of $49,900, its MIPS R3000 CPU generates 13 MIPS and 1 1/2 megaflops.</p>
<p>SGI has no plans to adjust the pricing of its low-end Personal Iris system line in response to IBM's offerings, according to Thomas Jermoluk, SGI's vice president of advanced systems divison. The systems use up to eight of the 25-MHz R3000 CPU chips in a symmetrical multiprocessing configuration. The Single-CPU Model 4D/210VGXB generates 20 MIPS or integer performance and 3.3 megaflops of double-precision floating-point operation, while the top-end configuration claims 160 MIPS and 28 megaflops. The Geometry Engines - VLSI chips that are part of SGI's graphics displays - perform image processing operations at 128 megaflops, and the Power Vision series claims a sustained display transfer rate of 18 million pixels per second. It will also fill at a rate of 100 to 200 million pixels per second.</p>
<p>"The Power Vision series is the only one that does anti-aliasing of polygons," Jermoluk said. The systems also contain the Sharp Scene Accumulation Buffer, which gives the system a place to store images for motion blur and full-scene progressive anti-aliasing.</p>
<p>Jermoluk rates the Power Vision series graphics as two orders of magnitude more powerful than the plain Personal Iris.</p>
<p>"The Personal Iris also doesn't have the level of anti-aliasing that the Power Vision series has. The new series has higher sampling rates, does it in real-time, and is more sophisticated in how it breaks images down into subpixels," Jermoluk said.</p>
<p>The Power Vision series also begins with 48 bits of color and a 24-bit Z buffer, while the Personal Iris begins with 8 bits of color and no Z buffer.</p>
<p>Both the IBM and Silicon Graphics systems use Silicon Graphics' GL graphics library calls, which make it easier for third-party developers to write applications code for both systems with a single ffort.</p>
<p>"As long as they use Motif and X Windows, they should be OK," Jermoluk said. "If they use a different window manager like Next Step, however, then they will have to rewrite that portion."</p>
<p>Silicon Graphics currently owns 50 percent of the 3-D workstation market, according to Montgomery Securities, and according to Dataquest, it represents 5.2 percent of the overall workstation market.</p>
<p>The Power Vision series wil begin shipping in June. The base price includes 8 megabytes of RAM (expandable to 128 megabytes at $4,000 per 8 megabytes) and no hard drive (a 380-megabyte hard drive adds $4,000 to the system price).</p>
